"""Initial

Revision ID: 0aff88365d4a
Revises: None
Create Date: 2026-06-30 08:56:10.493598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aff88365d4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_id_or_passport', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('dept_role', sa.String(length=30), nullable=True),
    sa.CheckConstraint("dept_role IN ('Department Head', 'Field Operator', 'Support Rep')", name='check_dept_role'),
    sa.CheckConstraint("role IN ('citizen', 'dept_admin', 'super_admin')", name='check_user_role'),
    sa.CheckConstraint("status IN ('active', 'suspended')", name='check_user_status'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_unique_department_head', ['department_id'], unique=True, sqlite_where=sa.text("dept_role = 'Department Head'"), postgresql_where=sa.text("dept_role = 'Department Head'"))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('pending_role_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_role_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_role_changes_id'), ['id'], unique=False)

    op.create_table('system_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_performed', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('previous_row_hash', sa.String(length=64), nullable=False),
    sa.Column('current_row_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_row_hash')
    )
    with op.batch_alter_table('system_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_audit_logs_id'), ['id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assigned_department_id', sa.Integer(), nullable=True),
    sa.Column('assigned_employee_id', sa.Integer(), nullable=True),
    sa.Column('reassignment_requested', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('proof_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_violated', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('citizen_satisfied', sa.Boolean(), nullable=True),
    sa.Column('reopened', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='check_ticket_priority'),
    sa.CheckConstraint("status IN ('processing', 'pending', 'in_progress', 'resolved', 'sla_violated', 'Under Re-evaluation')", name='check_ticket_status'),
    sa.ForeignKeyConstraint(['assigned_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('proof_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    with op.batch_alter_table('proof_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proof_requests_id'), ['id'], unique=False)

    op.create_table('ticket_clarifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_clarifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_clarifications_id'), ['id'], unique=False)

    op.create_table('ticket_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('clarification_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('is_proof', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['clarification_id'], ['ticket_clarifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_attachments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_attachments_id'))

    op.drop_table('ticket_attachments')
    with op.batch_alter_table('ticket_clarifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_clarifications_id'))

    op.drop_table('ticket_clarifications')
    with op.batch_alter_table('proof_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proof_requests_id'))

    op.drop_table('proof_requests')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('system_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_audit_logs_id'))

    op.drop_table('system_audit_logs')
    with op.batch_alter_table('pending_role_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_role_changes_id'))

    op.drop_table('pending_role_changes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_unique_department_head', sqlite_where=sa.text("dept_role = 'Department Head'"), postgresql_where=sa.text("dept_role = 'Department Head'"))

    op.drop_table('users')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    # ### end Alembic commands ###
