"""add_gis_coordinates_to_tickets

Revision ID: 11ddfe9f899f
Revises: f8a2c4e6d901
Create Date: 2026-06-23 13:14:08.047189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ddfe9f899f'
down_revision: Union[str, None] = 'f8a2c4e6d901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.drop_column('tickets', 'longitude')
    op.drop_column('tickets', 'latitude')
    op.create_index(op.f('ix_notifications_user_category'), 'notifications', ['user_id', 'category'], unique=False)
    # ### end Alembic commands ###
