"""add_citizen_feedback_columns

Revision ID: 2fa71306ca51
Revises: 8db72d208605
Create Date: 2026-06-23 14:35:05.194504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa71306ca51'
down_revision: Union[str, None] = '8db72d208605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('citizen_satisfied', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('reopened', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'reopened')
    op.drop_column('tickets', 'citizen_satisfied')
    # ### end Alembic commands ###
