"""add_parent_ticket_id

Revision ID: 3804836f7fea
Revises: 0aff88365d4a
Create Date: 2026-07-01 06:56:23.130026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3804836f7fea'
down_revision: Union[str, None] = '0aff88365d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_ticket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tickets_parent_ticket_id', 'tickets', ['parent_ticket_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_parent_ticket_id', type_='foreignkey')
        batch_op.drop_column('parent_ticket_id')

    # ### end Alembic commands ###
