"""add_system_audit_logs

Revision ID: 8db72d208605
Revises: 11ddfe9f899f
Create Date: 2026-06-23 13:56:36.082661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db72d208605'
down_revision: Union[str, None] = '11ddfe9f899f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_performed', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('previous_row_hash', sa.String(length=64), nullable=False),
    sa.Column('current_row_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_row_hash')
    )
    op.create_index(op.f('ix_system_audit_logs_id'), 'system_audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.create_index(op.f('ix_notifications_user_category'), 'notifications', ['user_id', 'category'], unique=False)
    op.drop_index(op.f('ix_system_audit_logs_id'), table_name='system_audit_logs')
    op.drop_table('system_audit_logs')
    # ### end Alembic commands ###
