"""add_roles_and_assignments

Revision ID: d491bf688d57
Revises: b1b1b1b1b1b1
Create Date: 2026-06-23 06:11:27.135363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd491bf688d57'
down_revision: Union[str, None] = 'b1b1b1b1b1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_role_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_role_changes_id'), 'pending_role_changes', ['id'], unique=False)
    op.add_column('tickets', sa.Column('assigned_employee_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('reassignment_requested', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('tickets', sa.Column('report', sa.Text(), nullable=True))
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_tickets_assigned_employee', 'users', ['assigned_employee_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_unique_department_head', 'users', ['department_id'], unique=True, sqlite_where=sa.text("dept_role = 'Department Head'"), postgresql_where=sa.text("dept_role = 'Department Head'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_unique_department_head', table_name='users', sqlite_where=sa.text("dept_role = 'Department Head'"), postgresql_where=sa.text("dept_role = 'Department Head'"))
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_assigned_employee', type_='foreignkey')
    op.drop_column('tickets', 'report')
    op.drop_column('tickets', 'reassignment_requested')
    op.drop_column('tickets', 'assigned_employee_id')
    op.drop_index(op.f('ix_pending_role_changes_id'), table_name='pending_role_changes')
    op.drop_table('pending_role_changes')
    # ### end Alembic commands ###
