"""add_employee_fields_to_users

Revision ID: e487c5b7bdc8
Revises: 6303ce72a6dc
Create Date: 2026-06-22 21:34:36.758825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e487c5b7bdc8'
down_revision: Union[str, None] = '6303ce72a6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ticket_attachments_id'), 'ticket_attachments', ['id'], unique=False)
    op.add_column('users', sa.Column('employee_id_or_passport', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'employee_id_or_passport')
    op.drop_index(op.f('ix_ticket_attachments_id'), table_name='ticket_attachments')
    # ### end Alembic commands ###
